### PR TITLE
Use env var and better search for PP names

### PR DESCRIPTION
**Pull request by farhi**
Hello,

I suggest the following improvement to your QE-ASE interface so that it runs smotthly with SSSP library, and environment variables.
I will create a Debian package so that installation is made easy for e.g. Ubuntu, including pyspglib.  

Detail of commit:
init: 
- Use ESPRESSO_PP_PATH env var as in ASE
- Use UPF format as default

writers: 
- search for PP also tries other possibilities for PP names, so that  a solution is found for e.g. SSSP library which is a mix.

### CODE REVIEW

**Comment by farhi** [comment]
Hello again, 

I have added smearing and electron mixing options, and fixed a conversion factor error when collecting the forces. This has been checked on e.g. the Al fcc phonon energies, as shown (expected in the 25 and 45 meV).
screenshot from 2016-07-28 14 29 00

**Comment by farhi** [comment]
I here attach a Debian package of qe-util, built on Ubuntu 14.04/amd64.
[python-ase-qe-spglib_0.1.16_amd64.deb.zip](https://github.com/jochym/qe-util/files/388366/python-ase-qe-spglib_0.1.16_amd64.deb.zip)

**Comment by jochym** [comment]
Nice. Thanks for the contribution @farhi ! One small issue though: pyspglib is now just spglib and the author prefers it to be distributed this way. Would you amend your PR?

**Comment by farhi** [comment]
Sure, but as I see in your code, you still have lines 

- from pyspglib import spglib

which are not in sync with the current spglib. At least for the Debian package, I think it makes sense to distribute a coherent choice of versions qe-util+spglib that just work. I could also create a specific spglib package but it takes time to build these packages and maintain them.

For the PR, the code change is anyway not related to spglib, only the Deb package.
BTW, all is now available at our Debain repo http;//packages.mccode.org.

Emmanuel.

**Comment by jochym** [comment]
Sorry for not responding quickly. The "canonical" way to import spglib now is:

```
try:
    import spglib as spg
except ImportError:
    from pyspglib import spglib as spg
```
This will make the code working regardless the version of the spglib in the environment.

**Comment by farhi** [comment]
Fully agree. I use this syntax in my own Python code as well.

**Comment by jochym** [comment]
Would you make the change? I will gladly merge the rest.

**Comment by farhi** [comment]
Just done that with the 2 above commits.

**Pull request merged**
