### PR TITLE
qeio.py: handle case with missing xml/DFT/LDA_PLUS_U token

### PR DESCRIPTION
**Pull request by farhi**
In some cases, the data-file.xml does not contain the DFT/LDA_PLUS_U token.
I thus added a test for token to exist (not None).

### CODE REVIEW

**Comment by jochym** [comment]
Thanks!

**Comment by jochym** [comment]
@farhi Emmanuel. I understand that you are using qe-util right now? Are you willing to cooperate, to bring it to the current standards? Particularly I need some tests to make it into a proper conda-forge package. I'm not using qe currently so the package is a bit neglected. But if I have somebody to test and cooperate I would put some effort into it.

**Comment by farhi** [comment]
Hi Pawel. I'm using QE-util only for its PWscf module so that ASE can basically compute phonons with it. 

However, the ASE Phonon module is currently not very useful as it lacks plenty of stuff and is very slow (and I think it is also wrong in the way it stores the force constants). 

So, these days I use QE-util together with PhonoPy, and the whole stuff within ASE. A kind of Russian puppet infrastructure, which takes the best of all packages for my peculiar use.

Having interacted with the ASE guys for some time, I think that QE-util should first be simplified so that it brings a minimalistic calculator. The gap for merge into ASE is then small. Afterwards, one can enrich the calculator with other capabilities that are today in QE-util.

**Comment by jochym** [comment]
Let us move to https://github.com/jochym/qe-util/issues/11 for the discussion.

**Pull request merged**
